# Generated by Django 3.2.12 on 2022-03-01 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0002_alter_slot_booking_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='hall_id',
            new_name='hall',
        ),
        migrations.AlterModelTable(
            name='slot',
            table='slot',
        ),
    ]
