# Generated by Django 3.2.12 on 2022-03-01 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0003_auto_20220301_0425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='booking_status',
            new_name='day',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='booking_date',
        ),
    ]
