# Generated by Django 3.2.12 on 2022-03-01 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0004_auto_20220301_0547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='day',
        ),
    ]
