# Generated by Django 3.2.12 on 2022-02-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='company_id',
            new_name='company',
        ),
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(max_length=150),
        ),
    ]
