# Generated by Django 3.2.12 on 2022-03-01 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferencehall', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conferncehall',
            old_name='company_id',
            new_name='company',
        ),
        migrations.AlterModelTable(
            name='conferncehall',
            table='conferencehall',
        ),
    ]
