# Generated by Django 3.2.12 on 2022-03-01 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='employee_id',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='slot_id',
            new_name='slot',
        ),
        migrations.AlterModelTable(
            name='booking',
            table='booking',
        ),
    ]
